name: ğŸš€ Publish package to NPM registry

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [semantic-release]

jobs:
  release:
    name: Build and release package
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”§ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ğŸŸ¢ Using Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: ğŸ— Install dependencies
        run: npm ci
      - name: ğŸ§ª Run tests
        run: npm t
      - name: ğŸ“¦ Release package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
