name: ğŸ”° Tests

# on:
#   push:
#     branches: ['*']
#   pull_request:
#     branches: ['*']

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_versions: [12.x]
        os: [ubuntu-latest]
    steps:
      - name: ğŸ”§ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ğŸŸ¢ Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: ğŸ— Install dependencies
        run: npm ci
      - name: ğŸ§ª Run tests
        run: npm test
